name: flet_secure_storage
description: Flet FletSecureStorage control
homepage: https://github.com/td3447/flet-secure-storage
repository: https://github.com/td3447/flet-secure-storage
issue_tracker: https://github.com/td3447/flet-secure-storage/issues
publish_to: none
version: 0.3.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flet: ^0.80.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0

topics:
  - flet
  - flutter
  - secure
  - storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
